name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
    
    - name: Build for macOS (Intel)
      run: |
        GOOS=darwin GOARCH=amd64 go build -o envelope-darwin-amd64 .
    
    - name: Build for macOS (Apple Silicon)
      run: |
        GOOS=darwin GOARCH=arm64 go build -o envelope-darwin-arm64 .
    
    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o envelope-windows-amd64.exe .
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          envelope-darwin-amd64
          envelope-darwin-arm64
          envelope-windows-amd64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 